version: '3.5'
services:
    php:
        image: maksim1990/symfony_helptranslate:latest
        container_name: helptranslate_php
        networks:
            - docker-shared-services
        user: "${UID}"
        volumes:
            - ./deploy:/var/www/deploy
            - ./images:/var/www/images
            - data-volume:/var/www
            - ./data/composer:/.composer
            - ./logs/symfony:/var/www/var/logs:cached
            - hosts-volume:/etc/nginx/conf.d
        depends_on:
            - redis
    nginx:
        image: nginx:latest
        networks:
            - docker-shared-services
        ports:
            - "${APP_HTTP_PORT}:80"
            - "${APP_HTTPS_PORT}:443"
        volumes:
            - ./images:/var/www/images
            - hosts-volume:/etc/nginx/conf.d
            - data-volume:/var/www
            - ./logs/nginx/:/var/log/nginx:cached
        depends_on:
            - php
    redis:
        image: redis:latest
        networks:
            - docker-shared-services
        ports:
          - "${APP_REDIS_PORT}:6379"
networks:
    docker-shared-services:
        external: true

volumes:
  data-volume:
  hosts-volume:
